const userData = [
  {
    student_id: 1001,
    name: "John",
    surname: "Doe",
    college: "Engineering",
    course: "Computer Science",
  },
  {
    student_id: 1002,
    name: "Jane",
    surname: "Smith",
    college: "Business",
    course: "Marketing",
  },
  {
    student_id: 1003,
    name: "Alex",
    surname: "Johnson",
    college: "Science",
    course: "Physics",
  },
  {
    student_id: 1004,
    name: "Emily",
    surname: "Davis",
    college: "Medicine",
    course: "Biology",
  },
  {
    student_id: 1005,
    name: "Chris",
    surname: "Miller",
    college: "Arts",
    course: "History",
  },
  {
    student_id: 1006,
    name: "Olivia",
    surname: "Brown",
    college: "Engineering",
    course: "Civil Engineering",
  },
  {
    student_id: 1007,
    name: "Ethan",
    surname: "Wilson",
    college: "Business",
    course: "Finance",
  },
  {
    student_id: 1008,
    name: "Sophia",
    surname: "Anderson",
    college: "Science",
    course: "Chemistry",
  },
  {
    student_id: 1009,
    name: "Logan",
    surname: "Taylor",
    college: "Medicine",
    course: "Nursing",
  },
  {
    student_id: 1010,
    name: "Ava",
    surname: "Moore",
    college: "Arts",
    course: "English Literature",
  },
  {
    student_id: 1011,
    name: "Mason",
    surname: "Martinez",
    college: "Engineering",
    course: "Electrical Engineering",
  },
  {
    student_id: 1012,
    name: "Amelia",
    surname: "Harris",
    college: "Business",
    course: "Management",
  },
  {
    student_id: 1013,
    name: "Caleb",
    surname: "Clark",
    college: "Science",
    course: "Computer Science",
  },
  {
    student_id: 1014,
    name: "Abigail",
    surname: "White",
    college: "Medicine",
    course: "Pharmacy",
  },
  {
    student_id: 1015,
    name: "Owen",
    surname: "Thomas",
    college: "Arts",
    course: "Music",
  },
  {
    student_id: 1016,
    name: "Harper",
    surname: "Lopez",
    college: "Engineering",
    course: "Mechanical Engineering",
  },
  {
    student_id: 1017,
    name: "Elijah",
    surname: "Adams",
    college: "Business",
    course: "Entrepreneurship",
  },
  {
    student_id: 1018,
    name: "Aria",
    surname: "Lee",
    college: "Science",
    course: "Biology",
  },
  {
    student_id: 1019,
    name: "Grayson",
    surname: "Scott",
    college: "Medicine",
    course: "Dentistry",
  },
  {
    student_id: 1020,
    name: "Lily",
    surname: "Baker",
    college: "Arts",
    course: "Visual Arts",
  },
  {
    student_id: 1021,
    name: "Isaac",
    surname: "Gonzalez",
    college: "Engineering",
    course: "Civil Engineering",
  },
  {
    student_id: 1022,
    name: "Evelyn",
    surname: "Young",
    college: "Business",
    course: "Marketing",
  },
  {
    student_id: 1023,
    name: "Jackson",
    surname: "Ward",
    college: "Science",
    course: "Physics",
  },
  {
    student_id: 1024,
    name: "Scarlett",
    surname: "Cooper",
    college: "Medicine",
    course: "Medical Science",
  },
  {
    student_id: 1025,
    name: "Lucas",
    surname: "Hill",
    college: "Arts",
    course: "Theater Arts",
  },
  {
    student_id: 1026,
    name: "Madison",
    surname: "Fisher",
    college: "Engineering",
    course: "Electrical Engineering",
  },
  {
    student_id: 1027,
    name: "Aiden",
    surname: "Barnes",
    college: "Business",
    course: "Finance",
  },
  {
    student_id: 1028,
    name: "Chloe",
    surname: "Miller",
    college: "Science",
    course: "Chemistry",
  },
  {
    student_id: 1029,
    name: "Mateo",
    surname: "Garcia",
    college: "Medicine",
    course: "Nursing",
  },
  {
    student_id: 1030,
    name: "Zoey",
    surname: "Russell",
    college: "Arts",
    course: "English Literature",
  },
  {
    student_id: 1031,
    name: "Ezra",
    surname: "Diaz",
    college: "Engineering",
    course: "Computer Engineering",
  },
  {
    student_id: 1032,
    name: "Grace",
    surname: "Turner",
    college: "Business",
    course: "Management",
  },
  {
    student_id: 1033,
    name: "Carter",
    surname: "Perez",
    college: "Science",
    course: "Computer Science",
  },
  {
    student_id: 1034,
    name: "Hannah",
    surname: "Evans",
    college: "Medicine",
    course: "Pharmacy",
  },
  {
    student_id: 1035,
    name: "Sebastian",
    surname: "Morgan",
    college: "Arts",
    course: "Drama",
  },
  {
    student_id: 1036,
    name: "Layla",
    surname: "Stewart",
    college: "Engineering",
    course: "Mechanical Engineering",
  },
  {
    student_id: 1037,
    name: "Wyatt",
    surname: "Reyes",
    college: "Business",
    course: "Entrepreneurship",
  },
  {
    student_id: 1038,
    name: "Addison",
    surname: "Ramirez",
    college: "Science",
    course: "Biology",
  },
  {
    student_id: 1039,
    name: "Henry",
    surname: "Wright",
    college: "Medicine",
    course: "Dentistry",
  },
  {
    student_id: 1040,
    name: "Nora",
    surname: "Woods",
    college: "Arts",
    course: "Visual Arts",
  },
  {
    student_id: 1041,
    name: "Leo",
    surname: "King",
    college: "Engineering",
    course: "Civil Engineering",
  },
  {
    student_id: 1042,
    name: "Henry",
    surname: "Bryant",
    college: "Business",
    course: "Marketing",
  },
  {
    student_id: 1043,
    name: "Henry",
    surname: "Hudson",
    college: "Science",
    course: "Physics",
  },
  {
    student_id: 1044,
    name: "Paisley",
    surname: "West",
    college: "Medicine",
    course: "Medical Science",
  },
  {
    student_id: 1045,
    name: "Landon",
    surname: "Ferguson",
    college: "Arts",
    course: "Music",
  },
  {
    student_id: 1046,
    name: "Aubrey",
    surname: "Fleming",
    college: "Engineering",
    course: "Electrical Engineering",
  },
  {
    student_id: 1047,
    name: "Oscar",
    surname: "Cruz",
    college: "Business",
    course: "Finance",
  },
  {
    student_id: 1048,
    name: "Brooklyn",
    surname: "Simmons",
    college: "Science",
    course: "Chemistry",
  },
  {
    student_id: 1049,
    name: "Eli",
    surname: "Gardner",
    college: "Medicine",
    course: "Nursing",
  },
  {
    student_id: 1050,
    name: "Sofia",
    surname: "Mills",
    college: "Arts",
    course: "English Literature",
  },
  {
    student_id: 1051,
    name: "Evan",
    surname: "Knight",
    college: "Engineering",
    course: "Computer Science",
  },
  {
    student_id: 1052,
    name: "Penelope",
    surname: "Rose",
    college: "Business",
    course: "Marketing",
  },
  {
    student_id: 1053,
    name: "Justin",
    surname: "Hayes",
    college: "Science",
    course: "Physics",
  },
  {
    student_id: 1054,
    name: "Avery",
    surname: "Ford",
    college: "Medicine",
    course: "Biology",
  },
  {
    student_id: 1055,
    name: "Hudson",
    surname: "Kennedy",
    college: "Arts",
    course: "History",
  },
  {
    student_id: 1056,
    name: "Violet",
    surname: "Harrison",
    college: "Engineering",
    course: "Civil Engineering",
  },
  {
    student_id: 1057,
    name: "Jaxon",
    surname: "Fisher",
    college: "Business",
    course: "Finance",
  },
  {
    student_id: 1058,
    name: "Henry",
    surname: "Bryant",
    college: "Science",
    course: "Chemistry",
  },
  {
    student_id: 1059,
    name: "Dominic",
    surname: "Dean",
    college: "Medicine",
    course: "Nursing",
  },
  {
    student_id: 1060,
    name: "Ariana",
    surname: "Fox",
    college: "Arts",
    course: "English Literature",
  },
  {
    student_id: 1061,
    name: "Rowan",
    surname: "Perry",
    college: "Engineering",
    course: "Electrical Engineering",
  },
  {
    student_id: 1062,
    name: "Bella",
    surname: "Fletcher",
    college: "Business",
    course: "Management",
  },
  {
    student_id: 1063,
    name: "Brayden",
    surname: "Howell",
    college: "Science",
    course: "Computer Science",
  },
  {
    student_id: 1064,
    name: "Leah",
    surname: "Hansen",
    college: "Medicine",
    course: "Pharmacy",
  },
  {
    student_id: 1065,
    name: "Nathan",
    surname: "Lawrence",
    college: "Arts",
    course: "Music",
  },
  {
    student_id: 1066,
    name: "Isla",
    surname: "Gibson",
    college: "Engineering",
    course: "Mechanical Engineering",
  },
  {
    student_id: 1067,
    name: "Henry",
    surname: "Murray",
    college: "Business",
    course: "Entrepreneurship",
  },
  {
    student_id: 1068,
    name: "Savannah",
    surname: "Myers",
    college: "Science",
    course: "Biology",
  },
  {
    student_id: 1069,
    name: "Eliana",
    surname: "Bowman",
    college: "Medicine",
    course: "Dentistry",
  },
  {
    student_id: 1070,
    name: "Ezra",
    surname: "Wells",
    college: "Arts",
    course: "Visual Arts",
  },
  {
    student_id: 1071,
    name: "Kai",
    surname: "Russell",
    college: "Engineering",
    course: "Civil Engineering",
  },
  {
    student_id: 1072,
    name: "Hazel",
    surname: "Webb",
    college: "Business",
    course: "Marketing",
  },
  {
    student_id: 1073,
    name: "Henry",
    surname: "Hart",
    college: "Science",
    course: "Physics",
  },
  {
    student_id: 1074,
    name: "Aubrey",
    surname: "Holmes",
    college: "Medicine",
    course: "Medical Science",
  },
  {
    student_id: 1075,
    name: "Gavin",
    surname: "Wagner",
    college: "Arts",
    course: "Drama",
  },
  {
    student_id: 1076,
    name: "Ariel",
    surname: "Shaw",
    college: "Engineering",
    course: "Electrical Engineering",
  },
  {
    student_id: 1077,
    name: "Hazel",
    surname: "Ray",
    college: "Business",
    course: "Finance",
  },
  {
    student_id: 1078,
    name: "Hazel",
    surname: "Black",
    college: "Science",
    course: "Chemistry",
  },
  {
    student_id: 1079,
    name: "Max",
    surname: "Fleming",
    college: "Medicine",
    course: "Nursing",
  },
  {
    student_id: 1080,
    name: "Hazel",
    surname: "Barnett",
    college: "Arts",
    course: "English Literature",
  },
  {
    student_id: 1081,
    name: "Jace",
    surname: "Castillo",
    college: "Engineering",
    course: "Computer Engineering",
  },
  {
    student_id: 1082,
    name: "Hazel",
    surname: "Williamson",
    college: "Business",
    course: "Management",
  },
  {
    student_id: 1083,
    name: "Parker",
    surname: "Hardy",
    college: "Science",
    course: "Computer Science",
  },
  {
    student_id: 1084,
    name: "Riley",
    surname: "Gomez",
    college: "Medicine",
    course: "Pharmacy",
  },
  {
    student_id: 1085,
    name: "Elena",
    surname: "Fuller",
    college: "Arts",
    course: "Dance",
  },
  {
    student_id: 1086,
    name: "Emmett",
    surname: "Nguyen",
    college: "Engineering",
    course: "Mechanical Engineering",
  },
  {
    student_id: 1087,
    name: "Athena",
    surname: "McCarthy",
    college: "Business",
    course: "Entrepreneurship",
  },
  {
    student_id: 1088,
    name: "Cameron",
    surname: "Howe",
    college: "Science",
    course: "Biology",
  },
  {
    student_id: 1089,
    name: "Lyla",
    surname: "McKenzie",
    college: "Medicine",
    course: "Dentistry",
  },
  {
    student_id: 1090,
    name: "Axel",
    surname: "Newton",
    college: "Arts",
    course: "Visual Arts",
  },
  {
    student_id: 1091,
    name: "Brielle",
    surname: "Wallace",
    college: "Engineering",
    course: "Civil Engineering",
  },
  {
    student_id: 1092,
    name: "Ezekiel",
    surname: "Whitaker",
    college: "Business",
    course: "Marketing",
  },
  {
    student_id: 1093,
    name: "Ivy",
    surname: "Richardson",
    college: "Science",
    course: "Physics",
  },
  {
    student_id: 1094,
    name: "Silas",
    surname: "Keller",
    college: "Medicine",
    course: "Medical Science",
  },
  {
    student_id: 1095,
    name: "Ellie",
    surname: "Holt",
    college: "Arts",
    course: "Music",
  },
  {
    student_id: 1096,
    name: "Jonah",
    surname: "Mathis",
    college: "Engineering",
    course: "Electrical Engineering",
  },
  {
    student_id: 1097,
    name: "Natalie",
    surname: "Rios",
    college: "Business",
    course: "Finance",
  },
  {
    student_id: 1098,
    name: "Kaiden",
    surname: "Huffman",
    college: "Science",
    course: "Chemistry",
  },
  {
    student_id: 1099,
    name: "Liam",
    surname: "McDonald",
    college: "Medicine",
    course: "Nursing",
  },
  {
    student_id: 1100,
    name: "Mackenzie",
    surname: "Solomon",
    college: "Arts",
    course: "English Literature",
  },
];

export {userData}
